ColorDefinition: Color Definition
PreslibClickMore: click here for more
PreslibId: Presentation Library Information
PreslibModule: Module
PreslibCOLS: Color Table 
PreslibLUPT: Lookup Table
PreslibLNST: Line Style
PreslibSYMB: Symbol
PreslibPATT: Pattern
PreslibEntries: entries
PreslibEXPP: Exchange Purpose 
PreslibPTYP: Product Type 
PreslibESID: Exchange Set Identification Number
PreslibEDTN: Edition Number
PreslibCO  : Compilation of Exchange Set
PreslibCODT: Compilation Date of Exchange Set
PreslibCOTI: Compilation Time of Exchange Set
PreslibVRDT: Library-Profile Versions Date
PreslibPROF: Library Application Profile
PreslibOCDT: Date of Version of applied Object Catalogue
PreslibCOMT: Comment
