Hello: Hello

ECDISShort: ECDIS
ECDISLong: ECDIS Version 0.1
ColorDefinition: Color Definition
PreslibId: Presentation Library Information
PreslibEXPP: Exchange Purpose 
PreslibPTYP: Product Type 
PreslibESID: Exchange Set Identification Number
PreslibEDTN: Edition Number
PreslibCO  : Compilation of Exchange Set
PreslibCODT: Compilation Date of Exchange Set
PreslibCOTI: Compilation Time of Exchange Set
PreslibVRDT: Library-Profile Versions Date
PreslibPROF: Library Application Profile
PreslibOCDT: Date of Version of applied Object Catalogue
PreslibCOMT: Comment
