Default: &defaults
  database: ecdis.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ecdis_test.sqlite3
  <<: *defaults

Staging:
  database: ecdis_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ecdis_production.sqlite3
  poolsize: 100
  <<: *defaults
